r-lib/withr

- tests/testthat/test-with.R
This may break on travis because par opens a new plot device when
called.
> Add tests for with_par

- man-roxygen/with.R
- man/with_collate.Rd
- man/with_dir.Rd
- man/with_envvar.Rd
- man/with_libpaths.Rd
- man/with_locale.Rd
- man/with_makevars.Rd
- man/with_options.Rd
- man/with_par.Rd
- man/with_path.Rd
- man/with_temp_libpaths.Rd
...or is this too much? Should we better alter the description of the `code` argument to include this information?
> document return type for all with_ functions

- .travis.yml
- R/devices.R
- R/seed.R
- man/devices.Rd
- tests/testthat/test-devices.R
- tests/testthat/test-namespace.R
> Test R 3.1 and 3.2

- NEWS.md
- R/options.R
- man/with_package.Rd
- tests/testthat/test-local.R
- do.call evaluates arguments, so in particular error = ... fails
- fixes r-lib/withr#73
> avoid `do.call()` when resetting options

- vignettes/withr.Rmd
I think the intention in the vignette was to refer to `setwd()` instead of `dir()` (i.e. `list.files()`)
> Change dir() to setwd() in withr vignette

- NEWS.md
- R/namespace.R
- man/with_package.Rd
Fixes #94 
Note the pre-existing warning in the master branch within Rd file. This PR introduces no new warnings.
> Remove `help` argument from `with_package()` and `local_package()`

- R/options.R
- man/with_options.Rd
local_options() is used to set an option with the scope of the function.
adding an example showing that while inside the function's scope, the
option is set and once outside of the function's scope, the option
returns to its previous value.
> adding example of using local_options()

- NEWS.md
- R/compat-defer.R
- tests/testthat/test-defer.R
This is a quick hack that suppresses the message and the immediate execution. However, the defered code is currently never run.
> Work in Rmd

- DESCRIPTION
- NEWS.md
- R/collate.R
- R/local_.R
- R/locale.R
- R/with_.R
- man/with_.Rd
- tests/testthat/helper.R
- tests/testthat/test-local.R
- tests/testthat/test-with.R
Part of #191.
- Adds `get` argument to `with_` and `local_`. When supplied, a restoration pattern robust to early exit during `set()` is used.
- Supply `get` when creating locale helpers. Should fix the testthat failures on Windows r-devel platforms.
> Use `old <- get()` idiom instead of `old <- set()` for robustness to early exits

- NEWS.md
- R/compat-defer.R
- tests/testthat/_snaps/defer.md
- tests/testthat/test-defer.R
Closes #136
Follow-up to #187
- Consistently use session scope inside knitr, no matter the evaluation environment.
- Do not use session scope with non-top-level evaluations in the global environment.
> Improve global env and knitr unwind

- NEWS.md
- R/namespace.R
When with_namespace() and local_namespace() gained a warn.conflicts
parameter in 4636e74 (Do not warn about conflicts by default,
2017-11-15), the underlying attach() calls were updated to pass a
hard-coded `warn.conflicts = FALSE`.  This was presumably
unintentional because 1) there's no comment or documentation about why
these functions expose warn.conflicts while ignoring it and 2) all
other functions in namespace.R propagate this argument.
Make with_namespace() and local_namespace() pass along the
warn.conflicts argument.
> with_namespace, local_namespace: Propagate warn.conflicts

- NEWS.md
- R/compat-defer.R
- R/utils.R
- tests/testthat/test-defer.R
Following Jenny's suggestion about "document scope", and Hadley's suggested implementation, `defer()` within `source()` and `knitr::knit()` now detects the relevant frame to register deferred expressions. This way, expressions are executed when `source()` and `knit()` return. In Rmd documents this gives `local_` functions "document scope" rather than "session scope".
The detection of `source()` adds 10 microseconds to every `defer()` call on an empty stack:
```r
bench::mark(
defer = local(defer(NULL))
)[1:8]
#> # main
#>   expression      min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 defer        17.2µs 18.7µs    46136.      280B     41.6  9991     9
#> # PR
#>   expression      min median `itr/sec` …
```
> Support `defer()` in `source()` and `knit()`

- R/compat-defer.R
Specifying `choices` is slightly faster than letting `match.arg()` look it up
``` r
fn1 <- function(x = c("a", "b", "c")) {
match.arg(x)
}
fn2 <- function(x = c("a", "b", "c")) {
match.arg(x, choices = c("a", "b", "c"))
}
bench::mark(
fn1(),
fn2(),
iterations = 100000
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 fn1()        6.82µs   7.75µs   115941.        0B     13.9
#> 2 fn2()        2.43µs   2.78µs   324765.        0B     19.5
```
> Explicitly specify `choices` for `match.arg()`

- DESCRIPTION
- NEWS.md
- R/defer.R
- R/seed.R
- R/standalone-defer.R
- R/utils.R
- tests/testthat/test-defer.R
- tests/testthat/test-standalone-defer.R
Branched from #220.
With this rewrite `defer()` is now a thin layer on top of `on.exit()`. This is possible thanks to two contributions that we made to R 3.5:
- Added argument for FIFO cleanup: `on.exit(after = FALSE)`
- Calling `sys.on.exit()` elsewhere than top-level didn't work. This is needed for manual invokation with `deferred_run()`.
Because of this change all users of the standalone file now need to update their file. Until they do, the order of execution of `defer()`-based handlers from different packages will not be correct because they no longer share the same data structure. I'm only aware of rlang and @gaborcsardi's packages that use a standalone defer.
One benefit of switching to `on.exit()` is that everything now shares the same data structure implemented in the R call …
> Implement `defer()` on top of `on.exit()`

- R/with_.R
- man/with_.Rd
It wasn't previously clear what the return value of the `set` parameter should be.
> Document the return value of `with_(set=)`

- tests/testthat/test-devices.R
Recommended packages are not available on all installations
> Optionally skip tests requiring 'lattice'

- tests/testthat/test-language.R
To ensure that reseting the cache afterwards is sufficient.
> Add extra test for with_langugage()

- R/defer.R
- tests/testthat/test-defer.R
Stopgap until we can figure out #235.
> Throw error when `deferred_run()` is run in knitted document

- NEWS.md
- R/defer-exit.R
- R/defer.R
- R/utils.R
- tests/testthat/_snaps/defer.md
- tests/testthat/test-defer.R
- vignettes/changing-and-restoring-state.Rmd
Branched from #250.
Closes #235.
Throwing an error causes a testthat vignette to fail (see https://github.com/r-lib/testthat/pull/1920). And now that we no longer use `exit_frame()` as the public interface for handling environments specially, it's easier to introduce special-casing for knitr. We now use the old approach of attaching a list of handlers to the knitr exit frame. This way our handlers are not mixed with knitr's own handlers and we can flush them separately.
Fixes the testthat failure in revdeps.
> Fix `deferred_run()` in knitr

- NEWS.md
- R/par.R
- tests/testthat/test-local.R
- tests/testthat/test-par.R
- tests/testthat/test-with.R
>  Call par() with no.readonly=TRUE to avoid warning

- NEWS.md
- R/language.R
Part of #254 and r-lib/testthat#1925.
We're going to use `local_language("C")` as a simple way of reliably disabling translations across platforms.
I'll do a quick patch release so that testthat can depend on this change.
> Never warn if `LANGUAGE` is set to `"C"`
