.Rbuildignore, tests/testthat/test-with.R
=> Fix Windows builds

R/with_.R, man/with_.Rd
=> Documentation: add typing and examples

README.Rmd, README.md
=> format function names

DESCRIPTION
https://twitter.com/xieyihui/status/590406807329222656
=> Satisfy spell checker

tests/testthat/test-with.R
=> create temporary output in /tmp

DESCRIPTION, R/collate.R, R/defer.R, R/dir.R, R/env.R, R/libpaths.R, R/locale.R, R/makevars.R, R/options.R, R/par.R, R/path.R, R/sink.R, R/with.R, R/with_.R, man/defer.Rd, man/with_dir.Rd, man/with_envvar.Rd, man/with_libpaths.Rd, man/with_locale.Rd, man/with_options.Rd, man/with_par.Rd, man/with_path.Rd, man/with_sink.Rd, man/with_temp_libpaths.Rd, man/withr.Rd
=> Convert documentation to Markdown

R/libpaths.R, R/local_.R, R/with_.R, man/with_.Rd, man/with_temp_libpaths.Rd, tests/testthat/test-with.R
Requires tweaking the metaprogramming a bit.
=> Add action argument to with_temp_libpaths()

NEWS.md, R/makevars.R, man/set_makevars.Rd, man/with_makevars.Rd
=> Use standard way of getting user makevars file

R/defer.R
Should I add a test using `callr` ?
=> inline defer in defer_parent. closes #79

R/path.R, man/with_path.Rd
Adding examples for `with_path()` function.
=> Adding examples for `with_path()`

README.Rmd, README.md
=> adds a number of functions in NAMESPACE that were missing in the Readme.rmd

R/env.R, man/with_envvar.Rd
=> add examples for with_envvar

R/collate.R, man/with_collate.Rd
=> Add examples for with_collate()

R/locale.R, man/with_locale.Rd
=> Added examples for with_locale()

NEWS.md, R/tempfile.R
=> add clean temp directories

DESCRIPTION, NEWS.md, R/seed.R, tests/testthat/test-seed.R, tests/testthat/test-with.R
=> Restore an unset `.Random.seed`

R/defer.R
=> Include `withr::` in this advice

NEWS.md, R/compat-defer.R, tests/testthat/test-defer.R
=> Throw errors if they happen in a deferred expression

NEWS.md, R/dir.R, R/env.R, R/file.R, R/libpaths.R, R/local_.R, R/locale.R, R/makevars.R, R/options.R, R/par.R, R/path.R, R/seed.R, R/utils.R, R/with_.R, man/devices.Rd, man/with_.Rd, man/with_collate.Rd, man/with_dir.Rd, man/with_envvar.Rd, man/with_file.Rd, man/with_libpaths.Rd, man/with_locale.Rd, man/with_makevars.Rd, man/with_options.Rd, man/with_par.Rd, man/with_path.Rd, man/with_sink.Rd, tests/testthat/test-defer.R, tests/testthat/test-local.R
=> Add `...` to some local_ functions, so they can be more easily called

.github/workflows/R-CMD-check.yaml
@jimhester do we need to document this somewhere in r-lib/actions?
=> Install xquartz

NEWS.md, R/env.R, R/file.R, R/libpaths.R, R/local_.R, R/options.R, R/par.R, R/path.R, R/seed.R, R/utils.R, R/with_.R
=> Use getter restoration pattern in remaining places

README.Rmd, README.md
=> README typo: conections -> connections

tests/testthat/test-language.R
Noticed as I was looking at these tests
=> Make a separate test

NEWS.md, R/local_.R, tests/testthat/test-local_.R
=> Ensure local_ works when withr isn't attached

R/defer.R, man/defer.Rd
=> Remove confusing globalenv() example

NEWS.md, R/devices.R, tests/testthat/helper.R, tests/testthat/test-devices.R
=> Restore previously opened device

NEWS.md, R/tempfile.R, man/with_tempfile.Rd, tests/testthat/test-tempfile.R
Fixes #209. Fixes #210. Fixes #216. Fixes #229.
cc @MichaelChirico
=> `local_tempfile()` improvements

R/collate.R, man/with_collate.Rd
=> Hardcode collation example
